# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import importparser_pb2 as importparser__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in importparser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImportParserServiceStub(object):
    """The main refactoring service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RefactorSingle = channel.unary_unary(
                '/com.decomp.monomorph.grpc.ImportParserService/RefactorSingle',
                request_serializer=importparser__pb2.RefactorSingleRequest.SerializeToString,
                response_deserializer=importparser__pb2.RefactorSingleResult.FromString,
                _registered_method=True)
        self.RefactorBatchTarget = channel.unary_unary(
                '/com.decomp.monomorph.grpc.ImportParserService/RefactorBatchTarget',
                request_serializer=importparser__pb2.RefactorBatchTargetRequest.SerializeToString,
                response_deserializer=importparser__pb2.RefactorSingleResult.FromString,
                _registered_method=True)
        self.RefactorAllTargets = channel.unary_stream(
                '/com.decomp.monomorph.grpc.ImportParserService/RefactorAllTargets',
                request_serializer=importparser__pb2.RefactorAllRequest.SerializeToString,
                response_deserializer=importparser__pb2.RefactorAllResult.FromString,
                _registered_method=True)


class ImportParserServiceServicer(object):
    """The main refactoring service
    """

    def RefactorSingle(self, request, context):
        """Mode 1: Single replacement in single target
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefactorBatchTarget(self, request, context):
        """Mode 2: Multiple replacements in single target
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefactorAllTargets(self, request, context):
        """Mode 3: Multiple replacements across multiple targets (Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImportParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RefactorSingle': grpc.unary_unary_rpc_method_handler(
                    servicer.RefactorSingle,
                    request_deserializer=importparser__pb2.RefactorSingleRequest.FromString,
                    response_serializer=importparser__pb2.RefactorSingleResult.SerializeToString,
            ),
            'RefactorBatchTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.RefactorBatchTarget,
                    request_deserializer=importparser__pb2.RefactorBatchTargetRequest.FromString,
                    response_serializer=importparser__pb2.RefactorSingleResult.SerializeToString,
            ),
            'RefactorAllTargets': grpc.unary_stream_rpc_method_handler(
                    servicer.RefactorAllTargets,
                    request_deserializer=importparser__pb2.RefactorAllRequest.FromString,
                    response_serializer=importparser__pb2.RefactorAllResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.decomp.monomorph.grpc.ImportParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.decomp.monomorph.grpc.ImportParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImportParserService(object):
    """The main refactoring service
    """

    @staticmethod
    def RefactorSingle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.decomp.monomorph.grpc.ImportParserService/RefactorSingle',
            importparser__pb2.RefactorSingleRequest.SerializeToString,
            importparser__pb2.RefactorSingleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefactorBatchTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.decomp.monomorph.grpc.ImportParserService/RefactorBatchTarget',
            importparser__pb2.RefactorBatchTargetRequest.SerializeToString,
            importparser__pb2.RefactorSingleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefactorAllTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.decomp.monomorph.grpc.ImportParserService/RefactorAllTargets',
            importparser__pb2.RefactorAllRequest.SerializeToString,
            importparser__pb2.RefactorAllResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
